"""add is_read column to user_books

Revision ID: aa3cefceb314
Revises: 292b6920f2ec
Create Date: 2019-10-29 13:17:48.730622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3cefceb314'
down_revision = '292b6920f2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'is_read')
    # ### end Alembic commands ###
